import { ActivityDefinition, Achievement, Tier, Category } from '@/types/domain';

export const TIERS: Tier[] = ['Beginner', 'Good', 'Elite', 'Master', 'Legendary'];

export const TIER_CONFIG: Record<
  Tier,
  { label: string; color: string; bgColor: string; borderColor: string; description: string; icon: string }
> = {
  Beginner: {
    label: 'Beginner',
    color: '#9CA3AF',
    bgColor: 'bg-gray-500/15',
    borderColor: 'border-gray-500/30',
    description: 'Fresh connection, initial casual interactions',
    icon: 'Sparkles',
  },
  Good: {
    label: 'Good',
    color: '#10B981',
    bgColor: 'bg-emerald-500/15',
    borderColor: 'border-emerald-500/30',
    description: 'Great chemistry and regular enjoyable meetups',
    icon: 'Smile',
  },
  Elite: {
    label: 'Elite',
    color: '#3B82F6',
    bgColor: 'bg-blue-500/15',
    borderColor: 'border-blue-500/30',
    description: 'High compatibility, deep talks and strong mutual vibe',
    icon: 'Zap',
  },
  Master: {
    label: 'Master',
    color: '#8B5CF6',
    bgColor: 'bg-purple-500/15',
    borderColor: 'border-purple-500/30',
    description: 'Unforgettable intimacy, trust and long-term potential',
    icon: 'Flame',
  },
  Legendary: {
    label: 'Legendary',
    color: '#F59E0B',
    bgColor: 'bg-amber-500/15',
    borderColor: 'border-amber-500/30',
    description: 'One in a million soul connection, top-tier romance',
    icon: 'Crown',
  },
};

export const CATEGORIES: Category[] = ['Dating', 'Social', 'Work', 'Other'];

export const STANDARD_ACTIVITIES: ActivityDefinition[] = [
  // First Impressions
  {
    id: 'first_convo',
    name: 'Exchanged Numbers / First Convo',
    xp: 25,
    description: 'Broke the ice and started a genuine conversation',
    category: 'First Impressions',
    icon: 'MessageCircle',
  },
  {
    id: 'first_coffee',
    name: 'Coffee / Casual Quick Meetup',
    xp: 50,
    description: 'Low-stakes first meetup that lasted over an hour',
    category: 'First Impressions',
    icon: 'Coffee',
  },
  {
    id: 'first_dinner_date',
    name: 'Proper First Dinner Date',
    xp: 100,
    description: 'Full evening dinner date with great ambient vibe',
    category: 'Dates & Hangouts',
    icon: 'Utensils',
  },
  {
    id: 'first_kiss',
    name: 'First Romantic Kiss',
    xp: 125,
    description: 'Electric spark when saying goodnight',
    category: 'Dates & Hangouts',
    icon: 'Heart',
  },
  {
    id: 'home_cooking',
    name: 'Cooked Dinner Together',
    xp: 150,
    description: 'Prepared a meal from scratch in your kitchen',
    category: 'Dates & Hangouts',
    icon: 'ChefHat',
  },
  {
    id: 'late_night_convo',
    name: 'Late-Night Deep Convo (3 AM)',
    xp: 150,
    description: 'Stayed up talking about life dreams and childhood fears',
    category: 'Milestones & Intimacy',
    icon: 'Moon',
  },
  {
    id: 'weekend_trip',
    name: 'Weekend Getaway / Road Trip',
    xp: 300,
    description: 'Traveled out of the city together for 48+ hours',
    category: 'Milestones & Intimacy',
    icon: 'Compass',
  },
  {
    id: 'met_the_friends',
    name: 'Introduced to the Inner Circle',
    xp: 200,
    description: 'Met best friends and passed the vibe check',
    category: 'Commitment & Special',
    icon: 'Users',
  },
  {
    id: 'unforgettable_night',
    name: 'Overnight Stay & Morning Coffee',
    xp: 250,
    description: 'Spent the entire night and made morning breakfast',
    category: 'Milestones & Intimacy',
    icon: 'Sun',
  },
  {
    id: 'exclusive_talk',
    name: 'The "What Are We?" / Exclusivity Talk',
    xp: 500,
    description: 'Had the defining relationship commitment conversation',
    category: 'Commitment & Special',
    icon: 'Award',
  },
];

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first_entry',
    title: 'First Entry',
    description: 'Add your first person to your private Hoekdex collection.',
    xpReward: 50,
    icon: 'UserPlus',
    criteria: '1 person added',
    maxProgress: 1,
    currentProgress: 1,
    isUnlocked: true,
    unlockedAt: '2026-08-10T14:32:00Z',
    category: 'collection',
  },
  {
    id: 'first_date_logged',
    title: 'First Date Logged',
    description: 'Record your very first milestone activity.',
    xpReward: 50,
    icon: 'CalendarHeart',
    criteria: '1 milestone claimed',
    maxProgress: 1,
    currentProgress: 1,
    isUnlocked: true,
    unlockedAt: '2026-08-11T19:45:00Z',
    category: 'milestone',
  },
  {
    id: 'xp_100',
    title: 'Novice Adventurer',
    description: 'Accumulate a total of 100 relationship XP.',
    xpReward: 100,
    icon: 'Sparkles',
    criteria: 'Earn 100 total XP',
    maxProgress: 100,
    currentProgress: 100,
    isUnlocked: true,
    unlockedAt: '2026-08-12T20:10:00Z',
    category: 'xp',
  },
  {
    id: 'xp_1000',
    title: 'Seasoned Raconteur',
    description: 'Reach 1,000 total XP across all your adventures.',
    xpReward: 250,
    icon: 'Flame',
    criteria: 'Earn 1,000 total XP',
    maxProgress: 1000,
    currentProgress: 675,
    isUnlocked: false,
    category: 'xp',
  },
  {
    id: 'xp_5000',
    title: 'Master of Hearts',
    description: 'Cross the 5,000 XP threshold into elite territory.',
    xpReward: 500,
    icon: 'Trophy',
    criteria: 'Earn 5,000 total XP',
    maxProgress: 5000,
    currentProgress: 675,
    isUnlocked: false,
    category: 'xp',
  },
  {
    id: 'ten_people_added',
    title: 'Extrovert Dynamo',
    description: 'Add 10 distinct people into your private records.',
    xpReward: 200,
    icon: 'Users',
    criteria: '10 people added',
    maxProgress: 10,
    currentProgress: 4,
    isUnlocked: false,
    category: 'collection',
  },
  {
    id: 'legendary_added',
    title: 'Legendary Encounter',
    description: 'Assign a person to the Legendary Tier.',
    xpReward: 300,
    icon: 'Crown',
    criteria: '1 person marked Legendary',
    maxProgress: 1,
    currentProgress: 1,
    isUnlocked: true,
    unlockedAt: '2026-08-14T22:15:00Z',
    category: 'special',
  },
  {
    id: 'weekly_top_3',
    title: 'Podium Finisher',
    description: 'Rank in the Top 3 on your weekly friend leaderboard.',
    xpReward: 200,
    icon: 'Medal',
    criteria: 'Top 3 on Weekly Leaderboard',
    maxProgress: 1,
    currentProgress: 0,
    isUnlocked: false,
    category: 'social',
  },
];
