import { Person, User, TimelineEvent, SocialPersonRef, FriendRequest } from '@/types/domain';
import { INITIAL_ACHIEVEMENTS } from './constants';

export const INITIAL_USER: User = {
  id: 'user_curr_01',
  email: 'mukesh@hoekdex.app',
  displayName: 'Mukesh Kumar',
  username: 'mukesh_k',
  avatarUrl: 'https://picsum.photos/seed/mukesh_avatar/200/200',
  totalXp: 675,
  currentRank: 3,
  leaderboardOptIn: true,
  allowFollowerXpView: true,
  createdAt: '2026-08-01T10:00:00Z',
  selectedAchievementBadge: 'Legendary Encounter',
};

export const INITIAL_PEOPLE: Person[] = [
  {
    id: 'person_maya_01',
    ownerId: 'user_curr_01',
    name: 'Maya Lin',
    photoUrl: 'https://picsum.photos/seed/maya_portrait/400/400',
    socialHandle: '@maya.design',
    dateFirstMet: '2026-07-15',
    category: 'Dating',
    notes: 'Met at the contemporary photography exhibition. Amazing dry wit and deep taste in Japanese coffee beans. Loved the jazz bar recommendation.',
    tier: 'Legendary',
    xpFromPerson: 375,
    activitiesClaimed: [
      {
        activityId: 'first_convo',
        activityName: 'Exchanged Numbers / First Convo',
        claimedAt: '2026-07-15T19:30:00Z',
        note: 'Talked about analogue cameras for 45 minutes straight.',
        xpAwarded: 25,
      },
      {
        activityId: 'first_dinner_date',
        activityName: 'Proper First Dinner Date',
        claimedAt: '2026-07-22T21:00:00Z',
        note: 'Tasting menu at Bar Goto. Super high chemistry.',
        xpAwarded: 100,
      },
      {
        activityId: 'first_kiss',
        activityName: 'First Romantic Kiss',
        claimedAt: '2026-07-22T23:45:00Z',
        note: 'Under the neon rain awning outside the station.',
        xpAwarded: 125,
      },
      {
        activityId: 'late_night_convo',
        activityName: 'Late-Night Deep Convo (3 AM)',
        claimedAt: '2026-08-04T03:15:00Z',
        note: 'Discussed architectural philosophies and personal mantras until sunrise.',
        xpAwarded: 150,
      },
    ],
    createdAt: '2026-07-15T20:00:00Z',
    updatedAt: '2026-08-14T22:15:00Z',
  },
  {
    id: 'person_elena_02',
    ownerId: 'user_curr_01',
    name: 'Elena Rostova',
    photoUrl: 'https://picsum.photos/seed/elena_portrait/400/400',
    socialHandle: '@elena_arch',
    dateFirstMet: '2026-07-28',
    category: 'Dating',
    notes: 'Met through mutual friends at the rooftop mixer. Very spontaneous energy, loves rock climbing and indie concerts.',
    tier: 'Elite',
    xpFromPerson: 175,
    activitiesClaimed: [
      {
        activityId: 'first_convo',
        activityName: 'Exchanged Numbers / First Convo',
        claimedAt: '2026-07-28T22:10:00Z',
        note: 'Exchanged playlists after bonding over 80s synth-pop.',
        xpAwarded: 25,
      },
      {
        activityId: 'first_coffee',
        activityName: 'Coffee / Casual Quick Meetup',
        claimedAt: '2026-08-02T16:00:00Z',
        note: 'Iced matcha at Blue Bottle before the gallery crawl.',
        xpAwarded: 50,
      },
      {
        activityId: 'first_dinner_date',
        activityName: 'Proper First Dinner Date',
        claimedAt: '2026-08-08T20:30:00Z',
        note: 'Sourdough pizza and spicy negronis. Super fun vibe.',
        xpAwarded: 100,
      },
    ],
    createdAt: '2026-07-28T22:30:00Z',
    updatedAt: '2026-08-08T21:00:00Z',
  },
  {
    id: 'person_clara_03',
    ownerId: 'user_curr_01',
    name: 'Clara Vance',
    photoUrl: 'https://picsum.photos/seed/clara_portrait/400/400',
    socialHandle: '@clara_v',
    dateFirstMet: '2026-08-05',
    category: 'Social',
    notes: 'Met at the design hackathon. Great sense of humor, always brings great culinary spots.',
    tier: 'Good',
    xpFromPerson: 75,
    activitiesClaimed: [
      {
        activityId: 'first_convo',
        activityName: 'Exchanged Numbers / First Convo',
        claimedAt: '2026-08-05T18:00:00Z',
        xpAwarded: 25,
      },
      {
        activityId: 'first_coffee',
        activityName: 'Coffee / Casual Quick Meetup',
        claimedAt: '2026-08-10T11:30:00Z',
        note: 'Quick espresso catchup before her product presentation.',
        xpAwarded: 50,
      },
    ],
    createdAt: '2026-08-05T19:00:00Z',
    updatedAt: '2026-08-10T12:00:00Z',
  },
  {
    id: 'person_sophie_04',
    ownerId: 'user_curr_01',
    name: 'Sophie Dubois',
    photoUrl: 'https://picsum.photos/seed/sophie_portrait/400/400',
    socialHandle: '@sophie.d',
    dateFirstMet: '2026-08-12',
    category: 'Dating',
    notes: 'Recently connected at the book club discussion. Fascinating perspective on existentialist fiction.',
    tier: 'Beginner',
    xpFromPerson: 50,
    activitiesClaimed: [
      {
        activityId: 'first_convo',
        activityName: 'Exchanged Numbers / First Convo',
        claimedAt: '2026-08-12T21:00:00Z',
        xpAwarded: 25,
      },
    ],
    createdAt: '2026-08-12T21:15:00Z',
    updatedAt: '2026-08-12T21:15:00Z',
  },
];

export const INITIAL_TIMELINE: TimelineEvent[] = [
  {
    id: 'event_01',
    eventType: 'achievement_unlocked',
    timestamp: '2026-08-14T22:15:00Z',
    achievementTitle: 'Legendary Encounter',
    achievementIcon: 'Crown',
    xpAwarded: 300,
  },
  {
    id: 'event_02',
    eventType: 'tier_change',
    timestamp: '2026-08-14T22:14:00Z',
    personId: 'person_maya_01',
    personName: 'Maya Lin',
    personPhotoUrl: 'https://picsum.photos/seed/maya_portrait/400/400',
    tier: 'Legendary',
  },
  {
    id: 'event_03',
    eventType: 'person_added',
    timestamp: '2026-08-12T21:15:00Z',
    personId: 'person_sophie_04',
    personName: 'Sophie Dubois',
    personPhotoUrl: 'https://picsum.photos/seed/sophie_portrait/400/400',
    tier: 'Beginner',
  },
  {
    id: 'event_04',
    eventType: 'milestone_unlocked',
    timestamp: '2026-08-10T11:30:00Z',
    personId: 'person_clara_03',
    personName: 'Clara Vance',
    personPhotoUrl: 'https://picsum.photos/seed/clara_portrait/400/400',
    activityName: 'Coffee / Casual Quick Meetup',
    xpAwarded: 50,
  },
  {
    id: 'event_05',
    eventType: 'milestone_unlocked',
    timestamp: '2026-08-08T20:30:00Z',
    personId: 'person_elena_02',
    personName: 'Elena Rostova',
    personPhotoUrl: 'https://picsum.photos/seed/elena_portrait/400/400',
    activityName: 'Proper First Dinner Date',
    xpAwarded: 100,
  },
  {
    id: 'event_06',
    eventType: 'note_memory',
    timestamp: '2026-08-04T03:30:00Z',
    personId: 'person_maya_01',
    personName: 'Maya Lin',
    noteText: 'Talked about Japanese mid-century aesthetics until 4 in the morning. Unforgettable connection.',
  },
  {
    id: 'event_07',
    eventType: 'milestone_unlocked',
    timestamp: '2026-08-04T03:15:00Z',
    personId: 'person_maya_01',
    personName: 'Maya Lin',
    personPhotoUrl: 'https://picsum.photos/seed/maya_portrait/400/400',
    activityName: 'Late-Night Deep Convo (3 AM)',
    xpAwarded: 150,
  },
];

/**
 * Social references - strictly limited to allowlisted fields!
 */
export const INITIAL_FRIENDS: SocialPersonRef[] = [
  {
    userId: 'friend_01',
    displayName: 'Alex Rivers',
    username: 'alex_rivers',
    avatarUrl: 'https://picsum.photos/seed/alex_friend/200/200',
    totalXp: 1450,
    weeklyXp: 450,
    monthlyXp: 950,
    rank: 1,
    achievementBadge: 'Seasoned Raconteur',
    isFollowing: true,
    isMutual: true,
  },
  {
    userId: 'friend_02',
    displayName: 'Jordan Cruz',
    username: 'jordan_cruz',
    avatarUrl: 'https://picsum.photos/seed/jordan_friend/200/200',
    totalXp: 980,
    weeklyXp: 320,
    monthlyXp: 680,
    rank: 2,
    achievementBadge: 'Master of Hearts',
    isFollowing: true,
    isMutual: true,
  },
  {
    userId: 'friend_03',
    displayName: 'Sam Chen',
    username: 'sam_chen',
    avatarUrl: 'https://picsum.photos/seed/sam_friend/200/200',
    totalXp: 520,
    weeklyXp: 150,
    monthlyXp: 410,
    rank: 4,
    achievementBadge: 'Novice Adventurer',
    isFollowing: true,
    isMutual: true,
  },
  {
    userId: 'friend_04',
    displayName: 'Taylor Swiftly',
    username: 'taylor_s',
    avatarUrl: 'https://picsum.photos/seed/taylor_friend/200/200',
    totalXp: 410,
    weeklyXp: 100,
    monthlyXp: 290,
    rank: 5,
    achievementBadge: 'First Date Logged',
    isFollowing: true,
    isMutual: false,
  },
  {
    userId: 'friend_05',
    displayName: 'Priya Sharma',
    username: 'priya_s',
    avatarUrl: 'https://picsum.photos/seed/priya_friend/200/200',
    totalXp: 320,
    weeklyXp: 80,
    monthlyXp: 210,
    rank: 6,
    achievementBadge: 'First Entry',
    isFollowing: false,
    isMutual: false,
  },
  {
    userId: 'friend_06',
    displayName: 'Marcus Thorne',
    username: 'marcus_t',
    avatarUrl: 'https://picsum.photos/seed/marcus_friend/200/200',
    totalXp: 890,
    weeklyXp: 250,
    monthlyXp: 600,
    rank: 7,
    achievementBadge: 'Legendary Encounter',
    isFollowing: false,
    isMutual: false,
  },
];

export const INITIAL_FRIEND_REQUESTS: FriendRequest[] = [
  {
    id: 'req_01',
    fromUserId: 'user_derek_07',
    fromDisplayName: 'Derek Miller',
    fromUsername: 'derek_m',
    fromAvatarUrl: 'https://picsum.photos/seed/derek_req/200/200',
    totalXp: 1120,
    rank: 3,
    badge: 'Master of Hearts',
    status: 'pending',
    createdAt: '2026-08-17T14:30:00Z',
  },
  {
    id: 'req_02',
    fromUserId: 'user_sara_08',
    fromDisplayName: 'Sara Kim',
    fromUsername: 'sara_k',
    fromAvatarUrl: 'https://picsum.photos/seed/sara_req/200/200',
    totalXp: 740,
    rank: 8,
    badge: 'Seasoned Raconteur',
    status: 'pending',
    createdAt: '2026-08-18T09:15:00Z',
  },
];

export const MOCK_SEARCHABLE_USERS: SocialPersonRef[] = [
  {
    userId: 'search_01',
    displayName: 'Leo Vance',
    username: 'leo_vance',
    avatarUrl: 'https://picsum.photos/seed/leo_search/200/200',
    totalXp: 1280,
    rank: 4,
    achievementBadge: 'Legendary Encounter',
  },
  {
    userId: 'search_02',
    displayName: 'Aria Stark',
    username: 'aria_s',
    avatarUrl: 'https://picsum.photos/seed/aria_search/200/200',
    totalXp: 910,
    rank: 9,
    achievementBadge: 'Seasoned Raconteur',
  },
  {
    userId: 'search_03',
    displayName: 'Noah Sterling',
    username: 'noah_sterling',
    avatarUrl: 'https://picsum.photos/seed/noah_search/200/200',
    totalXp: 650,
    rank: 12,
    achievementBadge: 'First Date Logged',
  },
  {
    userId: 'search_04',
    displayName: 'Zoe Kravitz',
    username: 'zoe_k',
    avatarUrl: 'https://picsum.photos/seed/zoe_search/200/200',
    totalXp: 1600,
    rank: 2,
    achievementBadge: 'Master of Hearts',
  },
];
